### ISSUE TITLE
Topo Factor assigned None in get_solar_flux() funtion in PyHeatsource

### ISSUE THREAD

**Issue by coltenelkin** [DEQrmichie/heatsource-9#14]
Running solar routine with land cover type height and get the following error:
`
Starting Model Initialization
Reading control file
Reading boundary conditions
  Reading boundary conditions 2905 2905 [...............................] 100%
Building Stream Nodes
  Building Stream Nodes 25 25 [.........................................] 100%
Translating Land Cover Data
  Reading vegetation heights 70 70 [....................................] 100%
  Building VegZones 26 26 [.............................................] 100%
Reading inflow data
Reading meteorological data
  Reading meteorological data 2905 2905 [...............................] 100%
  Subsetting met data 1 1 [.............................................] 100%
Assigning Meteorological Data to Nodes
  Assigning Node 26 26 [................................................] 100%
Model Initialization Complete
Starting Simulation:  SRSP as built left
Error: Traceback (most recent call last):                                 ] 0%
  File "C:\Users\CME1864\Miniconda3\envs\heatsource\lib\site-packages\heatsource9\BigRedButton.py", line 291, in run_solar
    HSP.run()
  File "C:\Users\CME1864\Miniconda3\envs\heatsource\lib\site-packages\heatsource9\BigRedButton.py", line 194, in run
    self.run_all(time, hour, minute, second, JD, JDC)
  File "C:\Users\CME1864\Miniconda3\envs\heatsource\lib\site-packages\heatsource9\BigRedButton.py", line 273, in run_sh
    [x.CalcHeat(time, H, M, S, JD, JDC, True) for x in self.reachlist]
  File "C:\Users\CME1864\Miniconda3\envs\heatsource\lib\site-packages\heatsource9\BigRedButton.py", line 273, in <listcomp>
    [x.CalcHeat(time, H, M, S, JD, JDC, True) for x in self.reachlist]
  File "src\heatsource9\Stream\StreamNode.pyx", line 378, in heatsource9.Stream.StreamNode.StreamNode.calc_heat_boundary_node
  File "src\heatsource9\Stream\PyHeatsource.pyx", line 822, in heatsource9.Stream.PyHeatsource.calc_heat_fluxes
  File "src\heatsource9\Stream\PyHeatsource.pyx", line 350, in heatsource9.Stream.PyHeatsource.get_solar_flux
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
`
I cannot compile a .pyd file on this workstation, but I wanted to try a simple fix by checking the Topo Factor for None in the get_solar_flux() function in PyHeatsource by adding two lines:
`
if not TopoFactor:
    TopoFactor = 0
`

No guarantees that'd work, but it was my initial thought.

**Comment by coltenelkin** [comment]
Took a while but I realized that this issue is the same as the one raised and solved by dharp on May 18. I went into the model_setup.py file and found where node.topo_factor is called out erroneously and changed it to node.TopoFactor (which matches all of the other callouts in the scripts). I
